title: 'Flammie'
subtitle: 'Flammie’s home pages'
navigation: 1
codeurl: 'https://github.com/flammie/flammie.github.io'
baseurl: ''
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM

theme: jekyll-theme-midnight